-- Create departamentos table
create table if not exists public.departamentos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  direccion text,
  precio_base numeric,
  max_huespedes integer
);

-- Create huespedes table
create table if not exists public.huespedes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  apellido text not null,
  telefono text,
  localidad text,
  patente_vehiculo text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create reservas table
create table if not exists public.reservas (
  id bigint generated by default as identity primary key,
  departamento_id bigint references public.departamentos(id) on delete cascade,
  huesped_id bigint references public.huespedes(id) on delete cascade,
  fecha_entrada date not null,
  fecha_salida date not null,
  estado_pago text check (estado_pago in ('consultado', 'seña', 'pagado')) default 'consultado',
  monto_total_pagar numeric,
  monto_sena numeric,
  cant_huespedes integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert dummy data for departamentos
insert into public.departamentos (nombre, direccion, precio_base)
values
  ('Depto A - Sea View', 'Av. Costanera 123', 100.00),
  ('Depto B - Garden', 'Calle 2 456', 80.00),
  ('Depto C - Penthouse', 'Av. Costanera 123', 200.00);

-- Enable RLS (optional for MVP but good practice)
alter table public.departamentos enable row level security;
alter table public.reservas enable row level security;

-- Create policies to allow all access (since it's internal admin only for now)
create policy "Allow all access to departamentos"
  on public.departamentos for all
  using (true)
  with check (true);

create policy "Allow all access to huespedes"
  on public.huespedes for all
  using (true)
  with check (true);

create policy "Allow all access to reservas"
  on public.reservas for all
  using (true)
  with check (true);
